name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        node_version: [16, 18, 20, 21]
        workspace:
          - "@neonpay/js"

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node_version: ${{ matrix.node_version }}
            cache: yarn
        - run: yarn install --immutable
        - run: yarn workspace ${{ matrix.workspace }} run check
        - run: yarn workspace ${{ matrix.workspace }} run test
